os: osx
language: rust
rust:
- stable
cache: cargo
script:
- cargo build
- cargo test --color always
before_deploy:
- make release
deploy:
  provider: releases
  file: {{WORKFLOWNAME}}.alfredworkflow
  skip_cleanup: true
  on:
    tags: true
