#!/bin/sh

__dirname=$(dirname "$(greadlink -f "$0")")
. "$(greadlink -f "$__dirname/../shared.sh")"

# define note
if [ -z "$1" ]; then
  printf 'What is the note about?\n❯ '
  read -r note
  if [ "$note" = "" ]; then
    printf 'no details provided, exiting\n'
    exit 1
  fi
else
  note="$1"
fi

note="$(echo "$note" | tr ' ' '-')"
now="$(now_iso)"
echo $now
touch "$now-$note.md"
